Repository acmucsd/main-website, pull requests merged in 2020-04, with the labels that each got.

#29 Navbar + Buttons: Fixed Navbar Color Spacing to Match Figma
  src/components/button/style.less
  src/index.tsx
  src/pages/navbar/style.less
Labels: Issue: New Feature, PR: Needs Review

#30 Buttons: Increased size to mirror figma
  src/components/button/style.less
Labels: PR: Needs Review

#32 Finished about us page without adding in sub-orgs
  src/assets/about-us.png
  src/pages/about-us/index.tsx
  src/pages/about-us/style.less
  src/pages/events/index.tsx
  src/pages/navbar/index.tsx
  src/pages/navbar/style.less
  src/pages/sponsorship/style.less
  yarn.lock
Labels: PR: Needs Review

#34 Major Airbnb refactoring
  .eslintrc.js
  .prettierrc.js
  .vscode/settings.json
  package-lock.json
  package.json
  src/api/EventsAPI.tsx
  src/components/button/index.tsx
  src/index.tsx
  src/pages/about-us/index.tsx
  src/pages/contact/index.tsx
  src/pages/events/index.tsx
  src/pages/home/index.tsx
  src/pages/navbar/index.tsx
  src/pages/sponsorship/index.tsx
  yarn.lock
Labels: PR: Good to Merge
