Repository acmucsd/main-website, pull requests merged in 2020-10, with the labels that each got.

#71 Update API Routes
  src/api/EventsAPI.tsx
Labels: PR: Good to Merge

#73 Update style for current website
  src/pages/home/index.tsx
  src/pages/home/style.less
  src/pages/navbar/index.tsx
Labels: PR: Needs Review, enhancement, hacktoberfest

#75 Add Get Involved Section
  src/assets/bit-byte.png
  src/assets/board.png
  src/assets/hackathon.png
  src/assets/projects.png
  src/index.tsx
  src/pages/get-involved/index.tsx
  src/pages/get-involved/style.less
Labels: PR: Needs Review

#76 Add Communities section
  src/assets/ai_logo.svg
  src/assets/cyber_logo.svg
  src/assets/design_logo.svg
  src/assets/hack_logo.svg
  src/assets/innovate_logo.svg
  src/index.tsx
  src/pages/communities/index.tsx
  src/pages/communities/style.less
  src/pages/home/index.tsx
  src/pages/home/style.less
  src/pages/navbar/index.tsx
Labels: PR: Needs Review, enhancement

#82 Squeeze Fix
  src/pages/get-involved/style.less
Labels: PR: Good to Merge

#83 Fix Side Project URL Typo
  src/pages/get-involved/index.tsx
Labels: PR: Good to Merge

#84 Color Variable Refactor
  package.json
  src/assets/ai_logo.svg
  src/assets/bit-byte.png
  src/assets/board.png
  src/assets/cyber_logo.svg
  src/assets/design_logo.svg
  src/assets/hack_logo.svg
  src/assets/hackathon.png
  src/assets/innovate_logo.svg
  src/assets/projects.png
  src/index.tsx
  src/pages/about/index.tsx
  src/pages/about/style.less
  src/pages/communities/index.tsx
  src/pages/communities/style.less
  src/pages/contact/style.less
  src/pages/events/style.less
  src/pages/get-involved/index.tsx
  src/pages/get-involved/style.less
  src/pages/home/index.tsx
  src/pages/home/style.less
  src/pages/navbar/index.tsx
  src/pages/navbar/style.less
  src/styles/colors.less
  yarn.lock
Labels: PR: Needs Review, enhancement

#86 Add auto scroll to events slider
  src/pages/events/index.tsx
Labels: PR: Needs Review, enhancement

#88 Update headers
  src/pages/about/index.tsx
  src/pages/about/style.less
  src/pages/communities/index.tsx
  src/pages/communities/style.less
  src/pages/events/index.tsx
  src/pages/events/style.less
  src/pages/get-involved/index.tsx
  src/pages/get-involved/style.less
  src/styles/mixins.less
Labels: PR: Needs Review, enhancement

#89 Fix header spacing
  src/pages/about/index.tsx
  src/pages/about/style.less
  src/pages/communities/index.tsx
  src/pages/communities/style.less
  src/pages/events/index.tsx
  src/pages/events/style.less
  src/pages/get-involved/index.tsx
  src/pages/get-involved/style.less
  src/pages/home/style.less
  src/styles/mixins.less
Labels: PR: Needs Review, enhancement

#90 Fix Communities Spacing
  src/pages/communities/index.tsx
  src/pages/communities/style.less
Labels: PR: Needs Review, enhancement

#91 Update images
  src/assets/bit-byte.png
  src/assets/board.png
  src/assets/cool_logo_1000x1000.png
  src/assets/hackathon.png
  src/assets/projects.png
  src/pages/about/style.less
Labels: enhancement

#96 Update hackathon image
  src/assets/hackathon.png
Labels: enhancement
